require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RScanner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'


  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  target 'RScannerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RScanner-tvOS' do
  # Pods for RScanner-tvOS

  target 'RScanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
